### ISSUE TITLE
Circumventing Railway Deployment

### ISSUE THREAD

**Issue by JakeCooper** [tuhinpal/WhatsBot#62]
Hi,

https://github.com/tuhinpal/WhatsBot/commit/d120cc88a245d7225b8077f93ba4636ba8fccbb0

Whatever this is is going to end up with your users getting banned on Railway

This is just a friendly warning; this isn't a supported and any attempts to get around it are against ToS

Please roll this back and remove the button

**Comment by tuhinpal** [comment]
Hello, Jake

It is removed https://github.com/tuhinpal/WhatsBot/commit/c0b87340ff197c8c19748b095a438f5b1c6db2ba

**Comment by creedxdd** [comment]
How can I scan the QR code?
