### ISSUE TITLE
YouTube Downloading Error 

### ISSUE THREAD

**Issue by pr13260** [tuhinpal/WhatsBot#69]
Commands !yt & !ytmusic 
links tried
https://m.youtube.com/watch?v=2Xq6Q7MUZaE
https://m.youtube.com/watch?v=fMALteQDp4I
https://m.youtube.com/watch?v=Ph9WRhlPacY
response
🙇‍♂️ *Error*

```Something Unexpected Happened to fetch the YouTube video```

Logs
Nothing there

**Comment by pr13260** [comment]
seems issues with site used in bot

**Comment by tuhinpal** [comment]
Yes, I will look into it soon

**Comment by pr13260** [comment]
> Yes, I will look into it soon

also a latency or ping time with pong in ping command would be loved 🙂

**Comment by tuhinpal** [comment]
P

**Comment by pr13260** [comment]
using https://en.savefrom.net/142/ instead https://sfrom.net/ would be much better 
both are same site but their default translation is arabic 
and people would love English 
this is about commands/yt.js save from net base url
